### ISSUE TITLE
Python3 version out of date, documentation doesn't work

### ISSUE THREAD

**Issue by tedivm** [citruspi/Flask-Analytics#11]
It's not appararent from the website that the python2 and python3 versions are completely different, even though they have the same version number. For instance, the python version is using the older out of data Google Analytics, and is using it with different keys than the python 2 version.

**Comment by citruspi** [comment]
> It's not appararent from the website that the python2 and python3 versions are completely different even though they have the same version number.

Sorry, could you expand on that? As far as I'm aware, the current code base should support both Python 2 and Python 3. I've run the same tests (on the same code base) using Python 2.7.9 and Python 3.5.0 without issues.

> For instance, the python version is using the older out of data Google Analytics, and is using it with different keys than the python 2 version.

After taking a quick look at PyPI, I've realized that I didn't push version `0.5.6` up - that's the version which added support for Google Universal Analytics. So, yep the documentation in the GitHub repo would be out of sync with the version that's currently up on PyPI.

I can push up version `0.5.6` sometime tonight or tomorrow and that should resolve the inconsistencies that you're seeing.

**Comment by citruspi** [comment]
Hey, I've run the tests again on my current machine (Python 2.7.12 and Python 3.5.2) and all the tests passed without an issue on the same codebase.

I've also changed the version from `0.5.6` to `0.6.0` since it is a breaking change and I've [uploaded the package to PyPI][0] as both a source distribution and a universal wheel.

Thanks for letting me know about the inconsistency and feel free to re-open the issue if you don't feel that this addresses your problem. 

[0]: https://pypi.python.org/pypi/Flask-Analytics/0.6.0

**Comment by tedivm** [comment]
The confusion here was in the different versions on pypi and here. When I came back here I saw that the python3 branch for this repository was using the out of date code and thought that, with the two branches, you were maintaining different versions for the different python versions.

**Comment by citruspi** [comment]
Gotcha, I was previously working on Python 3 support in that branch, I just forgot to delete it after support was merged in.

I've deleted the branch since it's no longer needed.
